myblog/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('blog/pub', views.pub_blog, name='pub_blog'),
    path('blog/comment/pub', views.pub_comment, name='pub_comment'),
    path('search/', views.search, name='search'),
]

myblog/blogauth/urls.py
from django.urls import path
from . import views

app_name = "blogauth"
urlpatterns = [
    path("login",views.mylogin,name="login"),
    path("register",views.register,name="register"),
    path("captcha",views.send_email_captcha,name="email_captcha"),
    path("logout",views.mylogout,name="logout"),
    path("profile/<int:user_id>/",views.profile,name="profile"),
    path("edit_profile/<int:user_id>/",views.edit_profile,name="edit_profile"),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('blogauth.urls')),
]

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height=50>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url "blog:pub_blog" %}" class="nav-link px-2 text-secondary">发布博客</a></li>
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="GET">
                <input type="search" name="q" class="form-control" placeholder="搜索..." aria-label="Search">
            </form>
            {% if user.is_authenticated %}
                <div class="dropdown text-end"><a href="#"
                                                  class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                                                  data-bs-toggle="dropdown" aria-expanded="false"> <img
                        src="{% static "image/user1.png" %}" alt="mdo" width="32" height="32" class="rounded-circle"> </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'blogauth:profile' user.id %}">个人简介</a></li>
                        <li><a class="dropdown-item" href="{% url 'blogauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                <a href="{% url 'blogauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'blogauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white border-bottom p-3">
    {% block main %}{% endblock %}
</main>
</body>
</html>

myblog/templates/blog_detail.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href={% static "highlight/styles/github-dark.min.css" %}>
    <script src={% static "highlight/highlight.min.js" %}></script>
{% endblock %}

{% block title %}博客详情{% endblock %}
{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/user.png' %}" alt="" height=30 class="rounded-circle">
        <span class="ms-2">
            <a href="{% url 'blogauth:profile' user_id=blog.author.id %}">
                {{ blog.author.username }}
            </a>
        </span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.time|date:"Y年m月d日 H时i分" }}</span> 发布
    </div>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论 （{{ blog.comments.all|length }}）</h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary mt-2">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2 text-body-secondary">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <div class="user-info">
                            <img src="{% static 'image/user.png' %}" alt="" height=30 class="rounded-circle">
                            <span class="ms-2">
                                <a href="{% url 'blogauth:profile' user_id=comment.author.id %}">
                                    {{ comment.author.username }}
                                </a>
                            </span>
                            <div class="mt-2">{{ comment.content }}</div>
                        </div>
                        <div class="create-time align-self-center">{{ comment.pub_time|date:"Y年m月d日 H时i分" }}</div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>hljs.highlightAll();</script>
{% endblock %}

myblog/templates/edit_profile.html
{% extends "base.html" %}
{% block title %}编辑个人简介{% endblock %}
{% block main %}
<h2>编辑个人简介</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">保存</button>
    <a href="{% url 'blogauth:profile' user_id=request.user.id %}" class="btn btn-secondary">取消</a>
</form>
{% endblock %}

myblog/templates/index.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
        {% for blog in blogs %}
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                    </div>
                    <div class="card-body" style="min-height: 100px">
                        <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                    </div>
                    <div class="card-footer text-body-secondary d-flex justify-content-between">
                        <div>
                            <img src="{% static 'image/user.png' %}" alt="" height=30 class="rounded-circle">
                            <span class="ms-2">
                                <a href="{% url 'blogauth:profile' user_id=blog.author.id %}">
                                    {{ blog.author.username }}
                                </a>
                            </span>
                        </div>
                        <div>
                            发布时间：{{ blog.time|date:"Y年m月d日 H时i分" }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a>
                        </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <span class="page-link">{{ num }}</span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
{% endblock %}

myblog/templates/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block main %}
    {% if form.email.error %}
        <div class="alert alert-danger">{{ form.email.error.0 }}</div>
    {% endif %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="checkDefault">
                <label class="form-check-label" for="checkDefault">
                    记住我
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

myblog/templates/profile.html
{% extends "base.html" %}
{% block title %}个人简介{% endblock %}
{% block main %}
<h2>{{ user.username }}</h2>
<p><strong>简介：</strong> {{ profile.bio|default:"这个人很神秘，还没有写简介。" }}</p>
<p><strong>所在地：</strong> {{ profile.location|default:"未填写" }}</p>
<p><strong>网站：</strong>
  {% if profile.website %}
    <a href="{{ profile.website }}" target="_blank">{{ profile.website }}</a>
  {% else %}
    未填写
  {% endif %}
</p>
{% if request.user.id == user.id %}
        <a href="{% url 'blogauth:edit_profile' user.id %}" class="btn btn-primary mt-3">
            编辑个人简介
        </a>
    {% endif %}
{% endblock %}

myblog/templates/pub_blog.html
{% extends "base.html" %}
{% block title %}发布博客{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
          #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
          }
          #toolbar-container {
            border-bottom: 1px solid #ccc;
          }
          #editor-container {
            height: 500px;
          }
    </style>
{% endblock %}
{% block main %}
<h1>发布博客</h1>
    <div class="mt-3">
        <form action="/" method="post">
        {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">博客标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

myblog/templates/register.html
{% extends "base.html" %}
{% block title %}注册{% endblock %}
{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>注册</h1>
        <form action="" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名"
                       value="{{ form.username.value|default:'' }}">
                {% for error in form.username.errors %}
                    <div class="text-danger small">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱"
                       value="{{ form.email.value|default:'' }}">
                {% for error in form.email.errors %}
                    <div class="text-danger small">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label>邮箱验证码</label>
                <div class="input-group">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码"
                           value="{{ form.captcha.value|default:'' }}">
                    <button class="btn btn-outline-secondary" type="button" id="captcha_btn">获取</button>
                </div>
                {% for error in form.captcha.errors %}
                    <div class="text-danger small">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
                {% for error in form.password.errors %}
                    <div class="text-danger small">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label>确认密码</label>
                <input type="password" name="confirmation" class="form-control" placeholder="确认密码">
                {% for error in form.confirmation.errors %}
                    <div class="text-danger small">{{ error }}</div>
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            <div class="mb-3">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}